### ISSUE TITLE
honoring the <xsd:sequence> tag in WSDL files

### ISSUE THREAD

**Issue by gvt** [vpulim/node-soap#355]
We are finding that the xsd:sequence tag in our WSDL files is not being honored by node-soap. As a result, SOAP calls fail because the order of the XML elements generated by node-soap does not match the order defined in the WSDL.

Example WSDL snippet:

```
<xsd:element name="fetchDeltaSince">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="auth" type="vin:Authentication" />
      <xsd:element name="timestamp" type="xsd:dateTime" />
      <xsd:element name="page" type="xsd:int" />
      <xsd:element name="pageSize" type="xsd:int" />
      <xsd:element minOccurs="0" name="endTimestamp" type="xsd:dateTime" />
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
```

Example XML output snippet:

```
<auth>...</auth>
<timestamp>2014-04-06T08:15:03-07:00</timestamp>
<endTimestamp>2014-04-06T09:15:03-07:00</endTimestamp>
<page/>
<pageSize>10</pageSize>
```

The problem in this example is that the `endTimestamp` element must be last in order to comply with the WSDL but instead it follows the `timestamp` element. This results in a SOAP Fault. I believe that the behavior of node-soap in this scenario does not comply with the SOAP standard.

Lastly, we are running version 0.1.2 of node-soap and not able to upgrade at the moment. Perhaps support for this has been added in a more recent version?

**Comment by Neppord** [comment]
I tried to go into the tests to see what parts explains this behaviure, but they are really a mess.

Could someone with more knowledge of this arcane codebase ;) tell me where tests should be written and how. Im used to mocha but these tests looks nothing like any mocha tests i have seen before. More like something homegrown.

Since with a test in place maybe i could fix this issue, since its really important for us that this works. The other option for us is to write our own lib for this small task.

Thanks!

**Comment by herom** [comment]
You're right as the codebase seems like a real mess... the [wsdl tests](https://github.com/vpulim/node-soap/blob/master/test/wsdl-test.js) are not really written with the `mocha` lib in mind, as it looks to me.

In general, tests which don't aim on some basic functionality (like utils, etc.) should go into our `request-response-samples` folder. 

**Every** contribution is very welcome!
