### ISSUE TITLE
Remove "tns" namespace to arguments

### ISSUE THREAD

**Issue by sameerjoshi** [vpulim/node-soap#369]
Hey @jsdevel , need your help with another issue. When I pass an argument to the WSDL method, the XML tags are containing "tns". These should not be there since the SOAP server, that I am working with is not able to parse this kind on request.

Below is the `client.lastRequest` for my call from `node-soap` that does not work

```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sidl="http://www.and.com/2007/03 /sidl" xmlns:tns="urn:and-com:document:and:rfc:functions">
   <soap:Header>
      <login>login</login>
      <password>pass</password>
      <namespace />
   </soap:Header>
   <soap:Body>
      <tns:SOME_METHOD xmlns="urn:and-com:document:and:rfc:functions">
         <tns:ARGUMENT>Master_Profile</tns:ARGUMENT>
      </tns:SOME_METHOD>
   </soap:Body>
</soap:Envelope>
```

Below is a request sent from `SOAP UI` that does work

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:and-com:document:and:rfc:functions">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:SOME_METHOD>
         <ARGUMENT>Master_Profile</ARGUMENT>
      </urn:SOME_METHOD>
   </soapenv:Body>
</soapenv:Envelope>
```

Any thoughts?

**Comment by bkapicka** [comment]
@sameerjoshi (or @jsdevel) Could you outline how you resolved this?  I have a similar issue with an external service (proprietary & specific SOAP envelope).

I could not find any native options that removed the tns from the first xml tag under the body.  I was able to hack the module to prevent these from being set (outlined below)

If I go into [client.js (line 185)](https://github.com/vpulim/node-soap/blob/master/lib/client.js#L185) and make the update below, it works just fine. (passing empty string as 3rd argument instead of 'input.targetNamespace')
```
// message = self.wsdl.objectToDocumentXML(input.$name, args, input.targetNSAlias, 'input.targetNamespace', (input.$type || input.$lookupType));
message = self.wsdl.objectToDocumentXML(input.$name, args, input.targetNSAlias, '', (input.$type || input.$lookupType));
```

**Comment by sameerjoshi** [comment]
@bkapicka What I did was, I checked existing structure of the proprietary which I was trying to connect. Then in the client.js made the changes accordingly so that ```node-soap``` could parse it properly with the respective tags.

Here is the forked repo that I corrected for my issue - https://github.com/BristleconeStore/node-soap-sap

Hope this helps.
