### ISSUE TITLE
How to set Soap version to 1.2 

### ISSUE THREAD

**Issue by adfoda3** [vpulim/node-soap#519]
Is it right, that node-soap uses only soap version 1.1? 
Or ist it possible to set it to version 1.2?
With 1.2 it shall use

xmlns:soap="http://www.w3.org/2003/05/soap-envelope/"

in the soap:envelope, instead of 

xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"

I'm wondering that the soap version is mentioned nowhere.

**Comment by mdhooge** [comment]
Hello,

I'm considering providing a PR for that issue. But I'm not a soap expert (and I don't really want to become one ^_^), so I'd happily have some guidelines!

Is the soap-envelope namespace the only change that must be applied to node-soap for it to become 1.2 compliant? This sounds too easy!

When I look at the client & the server code, the envelope creation is hard-coded. Wouldn't it be possible (and better) to use the wsdl generator? Because of the rpc/document differences, maybe we still need to do it in 2 passes and put the body afterwards inside the envelope.

Any other idea?

Michel

**Comment by aj2050** [comment]
any updates on setting soap version to 1.2 or an alternate way to make soap 1.2 request ?

**Comment by jsdevel** [comment]
@aj2050 nope.  We need a PR to add the support for it.
