### ISSUE TITLE
"Endpoint does not contain operation meta data"

### ISSUE THREAD

**Issue by ffxsam** [vpulim/node-soap#683]
I'm getting this error which took me quite a bit of time to trace. It came down to this:

The good `soapenv:Envelope` that actually works looks like this:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.supervisor.ws.five9.com/">
```

The bad envelope generated by this package looks like this:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:jaxws="http://java.sun.com/xml/ns/jaxws" xmlns:ns1="http://service.supervisor.ws.five9.com/v1/" xmlns:tns="http://service.supervisor.ws.five9.com/">
```

Why is it choosing those extra attributes and how can I strip them out and modify them?

**Comment by ffxsam** [comment]
I need to somehow add namespaces/schemas to the SOAP envelope.

**Comment by herom** [comment]
The SOAP Envelope is constructed [here](https://github.com/vpulim/node-soap/blob/master/lib/client.js#L190) which seems pretty "static". The programmatically added namespaces are taken from the `wsdl` "module" in `wsdl._xmlnsMap()` [here](https://github.com/vpulim/node-soap/blob/master/lib/wsdl.js#L1794).

I guess these two code points should point you in the right direction. If you could open a PR in order to "fix" this, this would be awesome :+1: (if you really have the time/availability to open a PR please see our [Guidelines on Submitting a PR](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) first).

**Comment by ffxsam** [comment]
Yeah, I saw this line:

     var xmlns = this.definitions.xmlns;

It *really* looks like these are being pulled from somewhere. I couldn't trace where `this.definitions.xmlns` is coming from.

It sucks that this isn't implemented. I needed it yesterday. :( I may just store the code in my project, hack it to what I need, and leave it at that.

**Comment by ffxsam** [comment]
But even if I manage to add the `ser="http://service.supervisor.ws.five9.com/"` namespace, its methods have to be called with the `ser:` prefix (e.g. `ser:getStatistics`), and I don't think this package supports calling methods like that.

**Comment by herom** [comment]
I'm aware that this library is far from being called feature-complete or bugfree. `node-soap` exists because of the community which contributes with fixes/features/etc., so if you found this library usefull and could contribute back this would be awesome :+1:

**Comment by ffxsam** [comment]
Oh man, I spent so many hours trying to get this to work. This explains a lot.

I would love to contribute except that I'm short on spare time. Also, the code is not documented very well, and so for some people such as myself who may have Javascript experience but aren't 100% familiar with Node's way of doing things, it's difficult to trace and figure out the process flow. Please, I urge all contributors to extensively document your code.

Thanks :)
