### ISSUE TITLE
is there a way to add a custom timeout for client requests ?

### ISSUE THREAD

**Issue by anvk** [vpulim/node-soap#734]
It does not seem there is an option anywhere in documentation for this.

**Comment by herom** [comment]
It's the 2nd point in our README [Module#options](https://github.com/vpulim/node-soap#options), stating that you can use `options` to not only override `node-soap` options, but also the options of the used `request` library (with link to the repository). :+1:

**Comment by anvk** [comment]
@herom this documentation is very confusing. I read it but still not sure how I suppose to override request options (or I need to override the whole request object?)

Also maybe it is subjective but me and lots of my co-workers find documentation very confusing in places.

**Comment by herom** [comment]
@anvk I agree that our documentation (sadly) lacks of structure and clarity. If you want to contribute to this project and make it better for others, please open a PR - this would be highly appreciated :+1: 

Other than this, the only way to find out about what's to set in the `options` object in order to override the `request` options is to dive into the code. I'm sorry to say this, but I haven't ever used it myself...
