### ISSUE TITLE
Close the SOAP Server

### ISSUE THREAD

**Issue by nkint** [vpulim/node-soap#751]
Hi!
I don't see any method to close the soap server. Can it causes memory leak during testing?

```
describe('heavily test some clients', function () {

  beforeEach(function(done) {

    const xml = require('fs').readFileSync(my_local_wsdl_mocked_files, 'utf8');
    mock = http.createServer(function(request,response) {
      response.end('404: Not Found: '+request.url)
    });
    mock.listen(8000);
    soapServer = soap.listen(mock, '/', myService, xml);

    done();
  });

  afterEach(function(done) {
    mock.close();
    mock = null;

    // how to close the soap server?
    // soapServer.close(); ?????
    soapServer = null;

    done();
  });

  it('should call the soap server', function(done){
     // here build a soap client and call it
     // my_local_wsdl_mocked_files contains a endpoint pointing at localhost
     // so the server mock will be called 
  });

});
```

**Comment by herom** [comment]
Hey @nkint,
you're right, at the moment there is no possibility to properly close the created `server` instance. A PR which addresses this bug/feature is highly welcome :+1: :smiley:

**Comment by marcusreese** [comment]
I'm not sure why this is both "completed" and "needs pull request" -- if completed, someone should document how to close a created soap server (i.e., deregister a path) without closing the http server that it is using

**Comment by w666** [comment]
@marcusreese 

Feel free to investigate this and open an issue or a pull request with the updated doc.
Are you affected by this?

**Comment by marcusreese** [comment]
We are affected, but instead of tackling it, I'm thinking we may refactor our code to try to avoid the issue. After investigation, my short answer guess is if you need to deregister a path and are willing to accept a small memory leak (because the old callback function will not be removed), you can probably call server.listen again for the same path somehow. 

Like would this work?
```
const replacementServer = http.createServer(function(request,response) {
      response.end('404: Not Found: ' + request.url);
  });
  replacementServer.listen(8000);
  soap.listen(replacementServer, { path });
```

To give more detail about the problem, server.ts constructor wsdl.onReady seems to have logic like the following pseudocode:
```
if (serverIsExpress) call express.route // which is also hard to remove without depending on express internals
else { // do something even harder to remove
  const previousRequestHandlers = copy of server.listeners('request')
  server.removeAllListeners('request');
  server.addListener('request', (req, res) => {
    if (pathIsMyPath) processRequest
    else call previousRequestHandlers 
  }
}
```

So it's effectively creating a closure-based linked list of functions, and removing one feels like climbing some stairs in a high-rise building and then deciding to remove whatever floor you're on. So if you want to support unlisten (unregistering a path), probably best to refactor it with a path-based lookup, something like this:
```
// soap.unlisten(path)
delete this.listenersByPath[path];
```

```
// soap.listen
this.listenersByPath[path] = fnWithAllNeededDetails
const genericListener = (req, res) => {
  respectAuthorizeConnection();
  if (this.listenersByPath[path]) {
    this.listenersByPath[path](req, res);
  }
}
if (isExpress(server)) {
  server.route(path).all(genericListener);
} else {
  server.removeListener('request', genericListener);
  server.addListener('request', genericListener);
}
  
```

**Comment by w666** [comment]
Do you mind to open a MR so we can discuss it there?
